server:
  port: 8091
eureka:
  client:
    # 表示是否注册自身到eureka服务器
    register-with-eureka: true
    # 是否从eureka上获取注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8092/eureka/
  server:
     enable-self-preservation: false
     eviction-interval-timer-in-ms: 2000